name: Jupyter to Python

on:
   push:
      branches: [main]
      paths-ignore:
         - "**.md"

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2
         - name: Set up Python 3.8.10
           uses: actions/setup-python@v2
           with:
              python-version: "3.8.10"

         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              pip install jupyter
              pip install nbconvert
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              
         - name: Black Check for Jupyter notebooks
           uses: marius-mather/black-check@jupyter
           
         - name: Commit formatted jupyter notebook files
           run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git diff --quiet && git diff --staged --quiet || git commit -m "format jupyter notebooks" -a

         - name: Convert Jupyter to Python
           run: |
              rm -rf python
              mkdir python
              for file in *.ipynb; do jupyter nbconvert --to script --output ./python/${file//.ipynb/} $file --TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input_prompt=True; done
              cd python
              sed -i 's/IS_NOTEBOOK: bool = True/IS_NOTEBOOK: bool = False/g' *.py
              cd ..

         - name: Commit python files
           run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git diff --quiet && git diff --staged --quiet || git commit -m "update python files" -a

         - name: Generate map image files
           run: |
              cd python
              for file in *.py; do python $file; done

         - name: Commit map image files
           run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git diff --quiet && git diff --staged --quiet || git commit -m "update map image files" -a

         - name: Run Jupyter Notebook
           run: |
              jupyter nbconvert --to notebook --inplace --execute *.ipynb

         - name: Commit Jupyter Notebooks
           run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              git diff --quiet && git diff --staged --quiet || git commit -m "update jupyter notbook results" -a

         - name: Push changes
           uses: ad-m/github-push-action@v0.6.0
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: main
